### ISSUE TITLE
Improve per-AS UI for humans

### ISSUE THREAD

**Issue by ttauber** [job/console.rpki-client.org#2]
With this output http://console.rpki-client.org/AS394018.html might it be possible to switch the columns so the ones that humans are interested in come on the left and the long one which has < 50 characters of useful stuff trails off the right or maybe is hidden in an href tag?

**Comment by job** [comment]
Columns have been swapped.

**Comment by job** [comment]
Fixed in https://github.com/job/console.rpki-client.org/commit/a409f26c13bac1ea0cf500ba0eae97443bcbaa53

**Comment by jkldgoefgkljefogeg** [comment]
Can you sort `Prefixes/Providers` to make it easier to spot duplicate ROAs?
